Add fields order
rs/zerolog pull request #550
Opened 2023-05-06 16:48 UTC by madkins23

After I did this work I saw PR 170 which is apparently languishing. My bad for not checking first. On the other hand this PR currently has no merge issues and I have time to respond to comments.

2023-05-09 16:13 UTC, madkins23 commented on console.go
> +		}
I agree and would have done it that way (and maybe saved the map on the `ConsoleWriter` for reuse) but the surrounding code was just iterating in a loop (see `FieldsExclude` just above) and I didn't want to break with the original author's style. Or worse yet start randomly fixing the existing loop(s).

That said, I don't mind making any reasonable change that will help the PR get accepted and merged.

2023-05-12 19:56 UTC, madkins23 commented on console.go
> +		}
Got a round toit.

2023-06-27 20:02 UTC, FlandiaYingman requested changes

2023-06-27 20:02 UTC, FlandiaYingman commented on .gitignore
I think you should remove this commit, because this is irrelevant with the feature we want to implement.

2023-06-27 20:02 UTC, FlandiaYingman commented on go.mod
The dependencies should not be updated by an feature implementing pull request for same reason: this is irrelevant with the feature we want to implement.

2023-06-28 03:24 UTC, madkins23 commented on .gitignore
Done

2023-06-28 03:25 UTC, madkins23 commented on go.mod
Done

2024-03-02 00:44 UTC, rs commented
Could you please make this change not allocating additional memory on each write if the feature is not used?

2024-03-02 18:04 UTC, madkins23 commented
Good idea. That also cleaned up the code a lot. Not sure what I was thinking when I did all that before. :-(

I stored a `map[string]bool` on the `ConsoleWriter` to speed up subsequent calls. It won't get created until the first call to `orderFields` so it's just a wasted pointer otherwise, and `ConsoleWriter` shouldn't be created a bunch of times unless I'm missing something.

BTW, there's another similar situation with `FieldsExclude` at the beginning of `ConsoleWriter.writeFields` that could be solved the same way.  The current solution iterates over `w.FieldsExclude` for each field which feels like `O(n^2)`. I don't mind writing the PR if you agree @rs.

Both of those last two notes assume that `ConsoleWriter` fields don't get changed over time. If that is not true then I need to remove that tweak on this PR. The `w.FieldsExclude` issue might still benefit from being converted to a `map[string]bool` at the beginning of  `ConsoleWriter.writeFields`.

2024-03-03 00:25 UTC, rs requested changes
Please consider the suggested changes to avoid allocations.

2024-03-03 00:25 UTC, rs commented on console.go
> +
```suggestion

	if len(w.FieldsOrder) > 0 {
		fields = w.orderFields(fields)
	} else {
		sort.Strings(fields)
	}

```

2024-03-03 00:25 UTC, rs commented on console.go
> +	return append(result, otherFields...)
```suggestion
	if w.fieldIsOrdered == nil {
		w.fieldIsOrdered = make(map[string]int)
		for i, fieldName := range w.FieldsOrder {
			w.fieldIsOrdered[fieldName] = i
		}
	}
	sort.Slice(fields, func(i, j int) bool {
		ii, iOrdered := w.fieldIsOrdered[fields[i]]
		jj, jOrdered := w.fieldIsOrdered[fields[j]]
		if iOrdered && jOrdered {
			return ii < jj
		}
		if iOrdered {
			return true
		}
		if jOrdered {
			return false
		}
		return fields[i] < fields[j]
	})
```

2024-03-03 00:54 UTC, madkins23 commented on console.go
> +
Done

2024-03-03 00:55 UTC, madkins23 commented on console.go
> +	return append(result, otherFields...)
Nice!

2024-03-03 01:13 UTC, rs approved these changes

2024-05-04 13:43 UTC, merged